include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # prefer_single_quotes: ignore
    # use_build_context_synchronously: ignore
    # prefer_const_constructors: ignore
    # prefer_const_declarations: ignore
    # unnecessary_nullable_for_final_variable_declarations: ignore
    # await_only_futures: ignore
    unintended_html_in_doc_comment: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    annotate_overrides: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_underscores: ignore
    sort_child_properties_last: ignore
    avoid_unnecessary_containers: ignore
    avoid_print: ignore
    strict_top_level_inference: ignore

